//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintTableNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debitor
    {
        public int Id { get; set; }
        public string Name_debitors { get; set; }
        public string Address { get; set; }
        public string Telefon { get; set; }
        public Nullable<decimal> Sum_debit { get; set; }
        public Nullable<decimal> Sum_credit { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
