//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintTableNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groupe
    {
        public int id { get; set; }
        public string Name_of_Groupe { get; set; }
    }
}
