//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintTableNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public int Id_of_Groupe { get; set; }
        public int Id_of_Products { get; set; }
        public string Name_of_Products { get; set; }
        public string Unit_of_Products { get; set; }
        public decimal Holesale_Price { get; set; }
        public decimal Sale_Price { get; set; }
        public Nullable<decimal> Quantity_of_Residual { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
