//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintTableNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int id { get; set; }
        public string Name_Suppliers { get; set; }
        public long TAX_ID_Suppliers { get; set; }
        public string Name_Responsible_Person { get; set; }
        public string Telefon { get; set; }
        public decimal Sum_Debit { get; set; }
        public decimal Sum_Credit { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
